name: Publish docs

on:
  push:
    branches:
      - master
      - jsdoc
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - run: corepack enable

      - name: Generate static docs
        run: |
          yarn install --immutable
          yarn run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
